[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; On pointe directement vers le dossier Common comme librairie extra
lib_extra_dirs = ..
lib_ldf_mode = deep+

lib_deps =
    adafruit/Adafruit BMP280 Library@^2.6.8
    adafruit/Adafruit Unified Sensor@^1.1.15
    adafruit/Adafruit BusIO@^1.17.4
    WiFiClientSecure
