[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; On pointe vers le dossier parent pour trouver Common/
lib_extra_dirs = ..
lib_ldf_mode = deep+

lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    WiFiClientSecure
