services:
  fog-service:
    image: ghcr.io/gaspardmenou/iot-rami-fog:latest
    restart: always
    environment:
      - MQTT_URL=mqtt://mosquitto
      - MQTT_PORT=1883
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
    depends_on:
      - mosquitto
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
  avahi:
    image: flungo/avahi:latest
    restart: always
    network_mode: host
    environment:
      - SERVER_HOST_NAME=rami-fog
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=300
      - DOCKER_API_VERSION=1.44