name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
    run:
      working-directory: ./umons-sensor-backend-1-feature-RAMI1-dev

jobs:
  lint :
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Lint the Dockerfile
      run: npm install && npm run format
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: npm install && npm run test
  build:
    needs: 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag umons-sensor-dev:$(date +%s)
  
  docker-push:
    needs: [lint, test]

    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v4
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set lowercase image name
      run: echo "IMAGE_NAME=ghcr.io/$(echo '${{ github.repository }}' | tr '[:upper:]'
        '[:lower:]')" >> $GITHUB_ENV
    - name: Build and push to GHCR
      uses: docker/build-push-action@v5
      with:
        context: ./umons-sensor-backend-1-feature-RAMI1-dev
        file: ./umons-sensor-backend-1-feature-RAMI1-dev/Dockerfile
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:${{ github.sha }}
          ${{ env.IMAGE_NAME }}:latest
